### ISSUE TITLE
FYI

### ISSUE THREAD

**Issue by tkellen** [yaymukund/grunt-ember-handlebars#3]
grunt.registerHelper will be depreciated in grunt 0.4.

To see how helpers will be handled in the future (using standard npm require), check out the following links:

https://github.com/gruntjs/grunt-contrib-uglify/blob/master/tasks/uglify.js#L15 https://github.com/gruntjs/grunt-contrib-uglify/blob/master/tasks/lib/min.js

**Comment by yaymukund** [comment]
Thanks a ton! I haven't dived into 0.4 yet, but I'll take a look when I get some time this week.
