### ISSUE TITLE
Seems to fail with latest Ember

### ISSUE THREAD

**Issue by rlopes** [yaymukund/grunt-ember-handlebars#8]
Hi,

It seems the task now fails with Ember-1.0.0-rc.1 and Handlebars-1.0.0-rc.3. Those 2 work together. I tried to update the task myself but NodeJS 'runInContext' is causing me grief and my limited Node experience doesn't allow me to track the problem for the moment.

Cheers,

Richard

**Comment by rlopes** [comment]
After digging I understood that Ember ditched the old way using ember-headless.js and now creates an ember-compile-templates.js file in its dist/ folder. By tweaking 2 lines and replacing ember.js by this file you bring the task up to the latest Ember and Handlebars version.

I need to look at pull requests but until then, here is the file as a Gist: https://gist.github.com/rlopes/4966479

**Comment by yaymukund** [comment]
Hi rlopes, thanks for the issue!

This should be fixed as of grunt-ember-handlebars 0.4.0. Please test and don't hesitate to reopen if you catch any bugs :+1:

**Comment by rlopes** [comment]
Happy to be of service. Thanks.
